--Previewing the first table
SELECT
  *
FROM
  "BRIGHT_TV"."PUBLIC"."VIEWERSHIP"
LIMIT
  10;

  
--Previewing the second table  
SELECT
  *
FROM
  "BRIGHT_TV"."PUBLIC"."USERPROFILES"
LIMIT
  10;

--Joining the two tables
WITH UsersAndViewership AS (
SELECT USERPROFILES.USERID, NAME, SURNAME, EMAIL, GENDER, RACE, AGE, PROVINCE, SOCIAL_MEDIA_HANDLE, CHANNEL2, RECORDDATE2, DURATION2,
FROM USERPROFILES
JOIN VIEWERSHIP ON VIEWERSHIP.USERID = USERPROFILES.USERID
)
SELECT *
FROM UsersAndViewership;

--Checking the minimum age
WITH UsersAndViewership AS (
SELECT USERPROFILES.USERID, NAME, SURNAME, EMAIL, GENDER, RACE, AGE, PROVINCE, SOCIAL_MEDIA_HANDLE, CHANNEL2, RECORDDATE2, DURATION2,
FROM USERPROFILES
JOIN VIEWERSHIP ON VIEWERSHIP.USERID = USERPROFILES.USERID
)
SELECT MIN(AGE)
FROM UsersAndViewership;

--Checking the maximum age
WITH UsersAndViewership AS (
SELECT USERPROFILES.USERID, NAME, SURNAME, EMAIL, GENDER, RACE, AGE, PROVINCE, SOCIAL_MEDIA_HANDLE, CHANNEL2, RECORDDATE2, DURATION2,
FROM USERPROFILES
JOIN VIEWERSHIP ON VIEWERSHIP.USERID = USERPROFILES.USERID
)
SELECT MAX(AGE)
FROM UsersAndViewership;

--Checking the different races
WITH UsersAndViewership AS (
SELECT USERPROFILES.USERID, NAME, SURNAME, EMAIL, GENDER, RACE, AGE, PROVINCE, SOCIAL_MEDIA_HANDLE, CHANNEL2, RECORDDATE2, DURATION2,
FROM USERPROFILES
JOIN VIEWERSHIP ON VIEWERSHIP.USERID = USERPROFILES.USERID
)
SELECT DISTINCT(RACE)
FROM UsersAndViewership;

--Checking different Provinces
WITH UsersAndViewership AS (
SELECT USERPROFILES.USERID, NAME, SURNAME, EMAIL, GENDER, RACE, AGE, PROVINCE, SOCIAL_MEDIA_HANDLE, CHANNEL2, RECORDDATE2, DURATION2,
FROM USERPROFILES
JOIN VIEWERSHIP ON VIEWERSHIP.USERID = USERPROFILES.USERID
)
SELECT DISTINCT(PROVINCE)
FROM UsersAndViewership;

--Checking the difeerent genders
WITH UsersAndViewership AS (
SELECT USERPROFILES.USERID, NAME, SURNAME, EMAIL, GENDER, RACE, AGE, PROVINCE, SOCIAL_MEDIA_HANDLE, CHANNEL2, RECORDDATE2, DURATION2,
FROM USERPROFILES
JOIN VIEWERSHIP ON VIEWERSHIP.USERID = USERPROFILES.USERID
)
SELECT DISTINCT(GENDER)
FROM UsersAndViewership;


--Processing
WITH UsersAndViewership AS (
    SELECT 
        UP.USERID, 
        NAME, 
        SURNAME, 
        EMAIL, 
        GENDER, 
        RACE, 
        AGE, 
        PROVINCE, 
        SOCIAL_MEDIA_HANDLE, 
        CHANNEL2, 
        RECORDDATE2, 
        DURATION2,
        CONVERT_TIMEZONE('UTC', 'Africa/Johannesburg', TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI')) AS LOCAL_TIMESTAMP
    FROM "BRIGHT_TV"."PUBLIC"."USERPROFILES" UP
    JOIN "BRIGHT_TV"."PUBLIC"."VIEWERSHIP" V ON V.USERID = UP.USERID
)
SELECT
    COUNT(DISTINCT USERID) AS Number_of_unique_viewers,
    TO_DATE(LOCAL_TIMESTAMP) AS the_date,
    DAYNAME(LOCAL_TIMESTAMP) AS day_name,
    MONTHNAME(LOCAL_TIMESTAMP) AS month_name,
    DAYOFMONTH(LOCAL_TIMESTAMP) AS day_of_month,
    TO_TIME(LOCAL_TIMESTAMP) AS the_time,
    GENDER, 
    RACE, 
    PROVINCE, 
    CHANNEL2,
    
    CASE 
        WHEN EXTRACT(HOUR FROM LOCAL_TIMESTAMP) BETWEEN 0 AND 5 THEN 'Early Morning'
        WHEN EXTRACT(HOUR FROM LOCAL_TIMESTAMP) BETWEEN 6 AND 11 THEN 'Morning'
        WHEN EXTRACT(HOUR FROM LOCAL_TIMESTAMP) BETWEEN 12 AND 17 THEN 'Afternoon'
        WHEN EXTRACT(HOUR FROM LOCAL_TIMESTAMP) BETWEEN 18 AND 23 THEN 'Evening'
    END AS Time_buckets,
    CASE
        WHEN AGE BETWEEN 0 AND 3 THEN 'Toddlers (0-3)'
        WHEN AGE BETWEEN 4 AND 12 THEN 'Kids (4-12)'
        WHEN AGE BETWEEN 13 AND 19 THEN 'Teenagers (13-19)'
        WHEN AGE BETWEEN 20 AND 30 THEN 'Young Adults (20-30)'
        WHEN AGE BETWEEN 31 AND 59 THEN 'Adults (31-59)'
        ELSE 'Seniors (60+)'
    END AS Age_groups
FROM UsersAndViewership
GROUP BY 
    the_date,
    day_name,
    month_name, 
    day_of_month,
    the_time,
    GENDER, 
    RACE, 
    PROVINCE, 
    CHANNEL2,
    Time_buckets,
    Age_groups;
